### ISSUE TITLE
Indicate computers with partial test suite runs

### ISSUE THREAD

**Issue by jschwab** [MESAHub/MESATestHub#12]
A computer is listed on the main page under "Computers tested" if it has reported any tests.  It would be helpful to have this list separated into computers that have run all tests and those that have run only some tests.

**Comment by rjfarmer** [comment]
I think we have an issue in that we don't know how many tests each version has. Either we need to add that information to the upload or at least just have a number after each computer's name stating how many tests they have submitted.

**Comment by wmwolf** [comment]
Life will be better when the GitHub migration occurs. Testhub will have its own version of the repo and can then just parse do1_test_source and figure out what tests it should expect to receive. This could be very useful for diagnosing incomplete test runs from computers that do things piecewise.

Some day...

Bill



On April 27, 2020 at 1:15:45 PM, Robert Farmer (notifications@github.com<mailto:notifications@github.com>) wrote:

I think we have an issue in that we don't know how many tests each version has. Either we need to add that information to the upload or at least just have a number after each computer's name stating how many tests they have submitted.

**Comment by jschwab** [comment]
Yeah, the `count_tests` script reports this number, so it should will be easy to report/record.

Keep hanging on Bill!  I can't even imagine what this semester has been like for you.

**Comment by wmwolf** [comment]
This addressed in the new version of the testhub. Closing.
