### ISSUE TITLE
Do something with submitted `MESA_RUN_OPTIONAL` data in submissions

### ISSUE THREAD

**Issue by wmwolf** [MESAHub/MESATestHub#25]
Submitted test instances now "know" when they came from running optional inlists. This should be saved into the database with the instances (and submissions) so that we can later search on them, they don't create spurious multiple checksum errors, don't pollute runtime statistics, etc.

**Comment by jschwab** [comment]
Test cases will also know if MESA_FPE_CHECKS_ON is set via the `fpe_checks` field.  Lumping that in here rather than creating a separate issue,  since it presumably requires similar handling.

**Comment by wmwolf** [comment]
At present, both of these statuses are now recorded in the database and are indicated in any list views showing individual test instances (viewing results of a test case for a particular commit or looking at history of instances from a particular computer for a particular test case).

Furthermore, `run_optional` instances are ignored in determining how many distinct checksums there are, so we won't get erroneous warnings for mixed checksums, even if there are distinct checksums between different instances that run optional inlists.

As the morning mailer (#17) gets rebuilt, we'll use this to filter out instances in determining average runtimes (and memory usage, maybe?).
