### ISSUE TITLE
Add open issue count to morning email

### ISSUE THREAD

**Issue by jschwab** [MESAHub/MESATestHub#27]
It'd be nice to have the number of open issues listed in the daily email (to motivate keeping it small).  That number should be easy to get with a single GH API call.

https://stackoverflow.com/a/33375166

**Comment by wmwolf** [comment]
A version of this is implemented that focuses only on release-blocking issues, along with a countdown to the next public release date.

I'm afraid having all open issues would be demoralizing and ultimately ignored.
