### ISSUE TITLE
Branch filter does not correctly apply on commit history page

### ISSUE THREAD

**Issue by jschwab** [MESAHub/MESATestHub#28]
For example, view https://testhub.mesastar.org/b3/test_cases/star/dev_pre_ms_to_cc_hi?utf8=%E2%9C%93&history_type=show_instances&start_date=2021-01-05&end_date=2021-01-06&computers=cannon_conroy_intel&status=&commit=Search

At the top, it shows that it is selecting the branch history of b3, but the first entry in the table is commit 26f70f4 which is not part of branch b3.

**Comment by wmwolf** [comment]
Is this still an issue? If so, is there a consistent way to reproduce it?

**Comment by jschwab** [comment]
TBH, I had enough frustrations with the test instances views that I just quit trying to use them a while back.  I can start using it again and filing new reproducible reports when things misbehave.
