### ISSUE TITLE
Add exit_code failure type

### ISSUE THREAD

**Issue by jschwab** [MESAHub/MESATestHub#34]
I am requesting the addition of a new failure type:

Entry in YAML file: "failure_type: :exit_code"
String for TestHub display: "Exit Code failure"

**Comment by wmwolf** [comment]
This exit code is now available for use.

**Comment by jschwab** [comment]
Thanks.  I enabled this in MESA `main`.

**Comment by jschwab** [comment]
Conveniently we got a few of these: https://testhub.mesastar.org/main/commits/7183cb2

Incredibly minor, but the word 'failure' is duplicated.  (I didn't know if it was part of the per-error string or template.)

**Comment by wmwolf** [comment]
That would have driven me crazy. Should be fixed now.
