### ISSUE TITLE
Failure to display TestHub extra quantities in multipart cases

### ISSUE THREAD

**Issue by jschwab** [MESAHub/MESATestHub#39]
Test Case-Specific Columns only show up in the 'Overview' part of the instance summary.  If you try and view them when limited to a single inlist (even the inlist during which they were generated), TestHub displays `data_hash[specific_col]`.

c13_pocket is the best example of multiple extra quantities generated in multiple parts.
https://testhub.mesastar.org/main/commits/451ed8c/test_cases/star/c13_pocket

**Comment by wmwolf** [comment]
Fixed! Thanks for catching this.
